site_name: dMail-docs

repo_name: 'ARintaro/dMail-docs'
repo_url: 'https://github.com/ARintaro/dMail-docs'

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs

nav:
  - dMail: 
    - Welcome: index.md
  - 技术文档:
    - 技术设计: tech/design.md
    - 连接服务端:
      - Cargo Doc: tech/backend/dMail/index.html 
    - 通信协议: 
      - Websocket: tech/network/websocket.md
    - 数据库:
      - redis:
        - user: tech/database/user.md
        - chat: tech/database/chat.md
        - req: tech/database/req.md
        - file: tech/database/file.md
  - 用户文档:
    - 使用帮助: 
      - Web端: user/help/web.md
    - 部署指南:
      - 服务端: user/deploy/server.md

plugins:
  - search
  - i18n:
      default_language: en
      docs_structure: suffix
      languages:
        en:
          name: English
          build: true
        zh:
          name: 中文
          build: true
      nav_translations:
        en:
          技术文档: Tech
          技术设计: Tech Design
          通信协议: Protocol
          数据库: Database
          用户文档: User
          使用帮助: Manual
          Web端: Web
          部署指南: Deploy
          服务端: Server
          连接服务端: Session Server